# 需求: 往控制台中输出Hello World, Hello Python (# Python中注释的写法, 注释是给开发热暖看的, python解释器会忽略注释)
# print("Hello World")
# print("Hello Python")
# print("-------------------")

print("# # # # # # # # # # #")
print("#   白 日 依 山 尽   #")
print("#   黄 河 入 海 流   #")
print("#   欲 穷 千 里 目   #")
print("#   更 上 一 层 楼   #")
print("# # # # # # # # # # #")